server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /springboot-consumer1
spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 10.88.128.65
    port: 6379
    timeout: 5s
    database: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #    driverClassName: com.mysql.cj.jdbc.Driver
    driverClassName: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://120.92.9.92:3306
    url: jdbc:mysql://localhost:3306/mrsoftrock?characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 12345678
    druid:
      keep-alive: true
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      log-abandoned: true

  data:
    elasticsearch:
      repositories:
        enabled: true
      client:
        reactive:
          endpoints: 10.128.88.65:9200
          use-ssl: true
          socket-timeout: 10s
#          password:



dubbo:
  application:
    name: dubbo-consumer
    qos-accept-foreign-ip: false
    qos-enable: false
  scan:
    basePackages: com.nacos.test
  provider:
    owner: mr.softrock
  protocol:
    name: dubbo
    port: 20880
    payload: 20971528
#    host: 120.92.78.198
  consumer:
    timeout: 600000
    lazy: true
    check: false
#  registry:
#    protocol: zookeeper
#    address: 120.92.78.198:2181
  registry:
    address: nacos://10.88.128.65:8848
#    parameters[namespace]: 8e6155c7-1149-4d45-a5f4-c87c2bbb4e47
  metadata-report:
    address: nacos://10.88.128.65:8848

nacos:
  config:
    server-addr: 10.88.128.65:8848
#    namespace: 2d4c5c4d-9ac8-4665-8eba-3b72345294e7
rocketmq:
  name-server: 10.88.128.65:9876
  producer:
    group: producer-nacos-consumer


