server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /springboot-consumer
spring:
  main:
    allow-bean-definition-overriding: true

dubbo:
  application:
    name: dubbo-consumer
    qos-accept-foreign-ip: false
    qos-enable: false
  scan:
    basePackages: com.nacos.test
  provider:
    owner: mr.softrock
  protocol:
    name: dubbo
    port: 20880
    payload: 20971528
#    host: 120.92.78.198
  consumer:
    timeout: 600000
    lazy: true
    check: false
#  registry:
#    protocol: zookeeper
#    address: 120.92.78.198:2181
  registry:
    address: nacos://120.92.78.198:8848
    parameters[namespace]: 8e6155c7-1149-4d45-a5f4-c87c2bbb4e47
  metadata-report:
    address: nacos://10.33.0.160:8848

nacos:
  config:
    server-addr: 120.92.78.198:8848
    namespace: 2d4c5c4d-9ac8-4665-8eba-3b72345294e7
rocketmq:
  name-server: 10.88.128.65:9876
  producer:
    group: producer-nacos-consumer


