server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /springboot-consumer
spring:
  main:
    allow-bean-definition-overriding: true
dubbo:
  application:
    name: dubbo-consumer
    qos-accept-foreign-ip: false
    qos-enable: false

  scan:
    basePackages: com.nacos
  provider:
    owner: mr.softrock
  protocol:
    name: dubbo
    port: -1
    payload: 20971528
  consumer:
    timeout: 10000
    lazy: true
    check: false
  registry:
    address: nacos://localhost:8848
nacos:
  config:
    server-addr: localhost:8848
    namespace: ad6d7661-8c8a-465f-ac35-0e6cb64f6480
#    data-id: springboot-nacos-test